"$schema" = "./node_modules/wrangler/config-schema.json"
name = "mtsphi"
compatibility_date = "2026-07-15"
compatibility_flags = ["nodejs_compat"]

main = "@tanstack/react-start/server-entry"

# --- Cloudflare D1 ---
[[d1_databases]]
binding = "DB"
database_name = "mts-alhidayatul-db"
database_id = "ac1f88c2-dfe5-4287-9107-279355cf0955"
migrations_dir = "drizzle/migrations"
